# permissions for end users to view pvcreclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvcreclaim-viewer-role
rules:
- apiGroups:
  - yibozhuang.me
  resources:
  - pvcreclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - yibozhuang.me
  resources:
  - pvcreclaims/status
  verbs:
  - get
